<template lang="html">
  <div class="termsconditions">
    <div class="t_and_c banner_t_and_c">
      <div class="container h-100 padding-top-lg ">
        <div class="row h-100 paddig-top-xl padding-bottom-lg">
          <div class="col-xl-12 col-md-12 col-sm-12 padding-xl">
            <div class="t_and_c_title margin-top-lg padding-xl text-center ">
              <p class="p1" style="text-align: center;"><span class="s1"><strong> Terms And Conditions</strong></span></p>
<p class="p2">&nbsp;</p>
<p class="p1"><span class="s1">Please read these terms of use (&ldquo;this Terms of Use&rdquo;) carefully before using this website, www.go4sightseeing.com (&ldquo;this Website&rdquo;) and the services offered by 9711368 CANADA INC, Maple labs and <a href="http://go4sightseeing.com"><span class="s2">go4sightseeing.com</span></a>. </span></p>
<p class="p3">&nbsp;</p>
<p class="p1"><span class="s1"><strong>1.&nbsp;Your Agreement</strong><br /> </span></p>
<p class="p1"><span class="s1">1.1 Your Acknowledgement</span></p>
<p class="p1" style="padding-left: 30px;"><span class="s1">1.1.1 Please read these terms of use (&ldquo;this Terms of Use&rdquo;) carefully before using this website, www.go4sightseeing.com (&ldquo;this Website&rdquo;) and the services offered by 9711368 CANADA INC (&ldquo;go4sightseeing&rdquo;) or the third party operators (&ldquo;the Operator&rdquo;) through this Website (&ldquo;the Services&rdquo;). &ldquo;You&rdquo;and &ldquo;your&rdquo; when used in this Terms of Use includes any person who accesses the Website.</span></p>
<p class="p3">&nbsp;</p>
<p class="p1"><span class="s1"><strong>2.&nbsp;Change / Modifications of Terms of Use</strong><br /> </span></p>
<p class="p1"><span class="s1">&nbsp;2.1 Go4sightseeing's Modifications</span></p>
<p class="p1" style="padding-left: 30px;">2.1.1 Go4sightseeing reserves the right, at its sole discretion, to change or modify any part of this Terms of Use at any time without prior notice. You should visit this page periodically to review the current Terms of Use to which you are bound. If Go4sightseeing changes or modifies this Terms of Use, Go4sightseeing will post the changes to or modifications of this Terms of Use on this page and will indicate at the top of this page the date on which this Terms of Use was last revised.</p>
<p class="p1" style="padding-left: 30px;"><span class="s1">2.1.2 Your continued use of this Website after any such changes or modifications constitutes your acceptance of the revised Terms of Use. If you do not agree to abide by the revised Terms of Use, do not use or access or continue to use or access this Website and/or the Services. It is your responsibility to regularly check this Website to ascertain if there are any changes to this Terms of Use and to review such changes.</span></p>
<p class="p1" style="padding-left: 30px;"><span class="s1">2.1.3 In addition, when using the Services, you shall be subject to any additional terms applicable to such Services that may be posted on the page relating to such Services from time to time and the privacy policy adopted by Go4sightseeing from time to time (&ldquo;the Privacy Policy&rdquo;). All such terms are hereby expressly incorporated by reference in this Terms of Use.</span></p>
<p class="p1" style="padding-left: 30px;">&nbsp;</p>
<p class="p1"><span class="s1"><strong>3.&nbsp;Access and Use of the Services</strong><br /> </span></p>
<p class="p1" style="padding-left: 30px;"><span class="s1">3.1 Ownership of Content<br /> </span></p>
<p class="p1" style="padding-left: 30px;"><span class="s1">3.1.1 This Website, the domain name (www.go4sightseeing.com), subdomains, features, contents and application services (including without limitation to any mobile application services) offered periodically by Go4sightseeing in connection therewith are owned and operated by Go4sightseeing.</span></p>
<p class="p1" style="padding-left: 30px;"><span class="s1"> <br /> 3.2 Provision and Accessibility of Services<br /> </span></p>
<p class="p1" style="padding-left: 30px;"><span class="s1">3.2.1 Subject to this Terms of Use, Go4sightseeing may either offer to provide the Services by itself or on behalf of the Operators, as described in further detail on this Website. The Services that have been selected by you on this Website are solely for your own use, and not for the use or benefit of any third party. The term "Services" includes but is not limited to the use of this Website, any Services offered by Go4sightseeing by itself or on behalf of the Operators on this Website. Go4sightseeing may change, suspend or discontinue any Services at any time, including the availability of any feature, database or content. Go4sightseeing may also impose limits or conditions on certain Services or restrict your access to any part or all of the Services without notice or liability.</span></p>
<p class="p1" style="padding-left: 30px;"><span class="s1">3.2.2 Go4sightseeing does not guarantee that the Services will always be available or uninterrupted. Go4sightseeing will not be liable to you if for any reason the Services are unavailable at any time or for any period. You are responsible for making all arrangements necessary for you to have access to the Services. You are also responsible for ensuring that all persons who access the Services through Internet connection are aware of this Terms of Use and other applicable terms and conditions for the Services, and that they comply with them.</span></p>
<p class="p1" style="padding-left: 30px;"><span class="s1">3.2.3 If you link to is Website, Go4sightseeing may revoke your rights to so link at any time, at Go4sightseeing&rsquo;s sole discretion. Go4sightseeing reserves the right to require prior written consent before linking to this Website.</span></p>
<p class="p1"><span class="s1"> <br /> </span></p>
<p class="p1"><span class="s1"><strong>4.&nbsp;Website and Content</strong><br /> </span></p>
<p class="p1" style="padding-left: 30px;"><span class="s1">4.1 Use of the Content<br /> <br /> </span><span class="s1">4.1.1 All materials displayed or performed on this Website including but not limited to text, data, graphics, articles, photographs, images, illustrations, video, audio and other materials (&ldquo;Content&rdquo;) are protected by copyright and/or other intellectual property rights. This Website and the Content are intended solely for your personal and non-commercial use of the Services and may only be used in accordance with this Terms of Use.</span></p>
<p class="p1" style="padding-left: 30px;"><span class="s1">4.1.2 If Go4sightseeing agrees to grant you access to this Website and/or the Content, such access shall be non-exclusive, non-transferable and limited license to access this Website in accordance with this Terms and Use. Go4sightseeing may, at its absolute discretion and at any time, without prior notice to you, amend or remove or alter the presentation, substance or functionality of any part or all of the Content from this Website.</span></p>
<p class="p1" style="padding-left: 30px;"><span class="s1">4.1.3 You shall abide by all copyright notices, trademark rules, information, and restrictions contained in this Website and the Content accessed through this Website, and shall not use, copy, reproduce, modify, translate, publish, broadcast, transmit, distribute, perform, upload, display, license, sell or otherwise exploit for any purposes whatsoever this Website or the Content or third party submissions or other proprietary rights not owned by you without the express prior written consent of the respective owners, or in any way that violates any third party rights.</span></p>
<p class="p1" style="padding-left: 30px;"><span class="s1"> <br /></span><span class="s1">4.2 Go4sightseeing&rsquo;s Liability for the Website and Content<br /> </span></p>
<p class="p1" style="padding-left: 30px;"><span class="s1">4.2.1 Go4sightseeing cannot guarantee the identity of any other users with whom you may interact with in the course of using this Website. Go4sightseeing cannot guarantee the authenticity and accuracy of any content, materials or information which other users or the Operators may provide. All Content accessed by you using this Website is at your own risk and you will be solely responsible for any damage or loss to any party resulting therefrom.</span></p>
<p class="p1" style="padding-left: 30px;"><span class="s1">4.2.2 Under no circumstances will Go4sightseeing be liable in any way for any Content, including but not limited to any errors or omissions in any Content, or any loss or damage of any kind incurred in connection with the use of or exposure to any Content posted, emailed, accessed, transmitted, or otherwise made available via this Website.</span></p>
<p class="p1"><span class="s1"> <br /> </span></p>
<p class="p1"><span class="s1">5.&nbsp;Intellectual Property Rights<br /> </span></p>
<p class="p1"><span class="s1">5.1 Intellectual Property<br /> </span></p>
<p class="p1"><span class="s1">5.1.1 All intellectual property rights subsisting in respect of this Website belong to Go4sightseeing or have been licensed to Go4sightseeing for use on this Website. This Website, the Services and the Content are protected by copyright and other intellectual property rights as collective works and/or compilations, pursuant to applicable copyright laws, international conventions, and other intellectual property laws. You undertake that:</span></p>
<p class="p1"><span class="s1">(a) You shall not modify, publish, transmit, participate in the transfer or sale of, reproduce, create derivative works based on, distribute, perform, display, or in any way exploit, any part of this Website and the Content, software, materials, or the Services in whole or in part;</span></p>
<p class="p1"><span class="s1">(b) You shall only download or copy the Content (and other items displayed on this Website or related to the Services) for personal and non-commercial use only, provided that you maintain all copyright and other notices contained in such Content; and</span></p>
<p class="p1"><span class="s1">(c) You shall not store any significant portion of any Content in any form. Copying or storing of any Content other than personal and noncommercial use is expressly prohibited without prior written permission from Go4sightseeing or from the copyright holder identified in such Contents copyright notice.</span></p>
<p class="p1"><span class="s1"> <br /> </span></p>
<p class="p1"><span class="s1"><strong>6.&nbsp;User Submissions</strong><br /> </span></p>
<p class="p1"><span class="s1">6.1 Uploading of Information<br /> </span></p>
<p class="p1" style="padding-left: 30px;"><span class="s1">6.1.1 In the course ofessing this Website or using the Services, you may provide information which may be used by Go4sightseeing and/or the Operators in connection with the Services and which may be visible to other users of this Website. You understand that by posting information or content on the Website or otherwise providing content, materials or information to Go4sightseeing and/or the Operators in connection with the Services (&ldquo;User Submissions&rdquo;):</span></p>
<p class="p1" style="padding-left: 60px;"><span class="s1">(a) You hereby grant to Go4sightseeing and the Operators a non-exclusive, worldwide, royalty free, perpetual, irrevocable, sub-licensable and transferable right to use and fully exploit such User Submissions, including all related intellectual property rights subsisted thereon, in connection with providing the Services and operating this Website and Go4sightseeing&rsquo;s business, including but not limited to the promotion and redistribution of part or all of the Services and derivative works thereof in any media formats and through any media channels;</span></p>
<p class="p1" style="padding-left: 60px;"><span class="s1">(b) You agree and authorize Go4sightseeing to use your personal data in accordance with the Privacy Policy in effect from time to time;</span></p>
<p class="p1" style="padding-left: 60px;"><span class="s1">(c) You hereby grant each user of this Website a non-exclusive license to access your User Submissions through this Website, and to use, modify, reproduce, distribute, prepare derivative works of, display and perform such User Submissions as permitted through the functionality of this Website and under this Terms of Use;</span></p>
<p class="p1" style="padding-left: 60px;"><span class="s1">(d) You acknowledge and agree that Go4sightseeing retains the right to reformat, modify, create derivative works of, excerpt, and translate any User Submissions submitted by you. For clarity, the foregoing license grant to Go4sightseeing does not affect your ownership of or right to grant additional non-exclusive licenses to the material in the User Submissions, unless otherwise agreed in writing; and</span></p>
<p class="p1" style="padding-left: 60px;"><span class="s1">(e) That all the User Submissions publicly posted or privately transmitted through this Website is the sole responsibility of you and that Go4sightseeing will not be liable for any errors or omissions in any content.</span></p>
<p class="p1"><span class="s1"> <br /> </span></p>
<p class="p1"><span class="s1"><strong>7.&nbsp;Users Representations, Warranties and Undertakings</strong><br /> </span></p>
<p class="p1" style="padding-left: 30px;"><span class="s1">7.1 Use of this Website and the Services<br /> <br /> </span></p>
<p class="p1" style="padding-left: 60px;"><span class="s1">7.1.1 You represent, warrant and undertake to Go4sightseeing that you will not provide any User Submissions or otherwise use this Website or the Services in a manner that:<br /> </span></p>
<p class="p1" style="padding-left: 90px;"><span class="s1">(a) Infringes or violates the intellectual property rights or proprietary rights, rights of publicity or privacy, or other rights of any third party; or</span></p>
<p class="p1" style="padding-left: 90px;"><span class="s1">(b) Violates any law, statute, ordinance or regulation; or</span></p>
<p class="p1" style="padding-left: 90px;"><span class="s1">(c) Is harmful, fraudulent, deceptive, threatening, abusive, harassing, tortious, defamatory, vulgar, obscene, libelous, or otherwise objectionable; or</span></p>
<p class="p1" style="padding-left: 90px;"><span class="s1">(d) Involves commercial activities and/or sales without Go4sightseeing&rsquo;s prior written consent such as contests, sweepstakes, barter, advertising, or pyramid schemes; or</span></p>
<p class="p1" style="padding-left: 90px;"><span class="s1">(e) Constitutes libel, impersonates any person or entity, including but not limited to any employee or representative of Go4sightseeing; or</span></p>
<p class="p1" style="padding-left: 90px;"><span class="s1">(f) Contains a virus, trojan horse, worm, time bomb, or other harmful computer code, file, or program.</span></p>
<p class="p1"><span class="s1"> <br /> <br /> </span></p>
<p class="p1" style="padding-left: 30px;"><span class="s1">7.2 Removal of User Submissions<br /> <br /> </span></p>
<p class="p1" style="padding-left: 60px;"><span class="s1">7.2.1 Go4sightseeing reserves the right to remove any User Submissions from this Website at any time, for any reason including but not limited to, receipt of claims or allegations from third parties or authorities relating to such User Submission or if Go4sightseeing is concerned that you may have breached any of the preceding representations, warranties or undertakings, or for no reason at all.</span></p>
<p class="p1" style="padding-left: 60px;"><span class="s1"> <br /> <br /> </span></p>
<p class="p1" style="padding-left: 30px;"><span class="s1">7.3 Responsibility for User Submissions<br /> </span></p>
<p class="p1" style="padding-left: 60px;"><span class="s1">7.3.1 You remain solely responsible for all User Submissions that you upload, post, email, transmit, or otherwise disseminate using, or in connection with, this Website.</span></p>
<p class="p1" style="padding-left: 60px;"><span class="s1">7.3.2 You acknowledge and agree that you shall be solely responsible for your own User Submissions and the consequences of posting or publishing all of your User Submissions on this Website. You represent, warrant and undertake to Go4sightseeing that:</span></p>
<p class="p3" style="padding-left: 60px;">&nbsp;</p>
<p class="p1" style="padding-left: 90px;"><span class="s1">(a) You own or have the necessary rights, licenses, consents, releases and/or permissions to use and authorize Go4sightseeing to use all copyright, trademark or other proprietary or intellectual property rights in and to any User Submission to enable inclusion and use thereof as contemplated by this Website and this Terms of Use; and</span></p>
<p class="p1" style="padding-left: 90px;"><span class="s1">(b) Neither the User Submissions nor your posting, uploading, publication, submission or transmittal of the User Submission or Go4sightseeing&rsquo;s use of the User Submissions, or any portion thereof, on or through this Website and/or the Services will infringe, misappropriate or violate any third party&rsquo;s patent, copyright, trademark, trade secret, moral rights or other proprietary or intellectual property rights, or rights of publicity or privacy, or result in the violation of any applicable law, rule or regulation.</span></p>
<p class="p3" style="padding-left: 90px;">&nbsp;</p>
<p class="p1" style="padding-left: 60px;"><span class="s1">7.3.3 You are responsible for all of your activity in connection with using this Website and/or the Services. You further represent, warrant and undertake to Go4sightseeing that you shall not:</span></p>
<p class="p3">&nbsp;</p>
<p class="p1" style="padding-left: 90px;"><span class="s1">(a) Conduct any fraudulent, abusive, or otherwise illegal activity which may be grounds for termination of your right to access or use this Website and/or the Services; or</span></p>
<p class="p1" style="padding-left: 90px;"><span class="s1">(b) Post or transmit, or cause to be posted or transmitted, any communication or solicitation designed or intended to obtain password, account, or private information from any other user of this Website; or</span></p>
<p class="p1" style="padding-left: 90px;"><span class="s1">(c) Violate the security of any computer network, crack passwords or security encryption codes, transfer or store illegal material (including material that may be considered threatening or obscene), or engage in any kind of illegal activity that is expressly prohibited; or</span></p>
<p class="p1" style="padding-left: 90px;"><span class="s1">(d) Run maillist, listserv, or any other form of auto-responder, or "spam" on this Website, or any processes that run or are activated while you are not logged on to this Website, or that otherwise interfere with the proper working of or place an unreasonable load on this Website&rsquo;s infrastructure; or</span></p>
<p class="p1" style="padding-left: 90px;"><span class="s1">(e) Use manual or automated software, devices, or other processes to "crawl," "scrape," or "spider" any page of this Website; or</span></p>
<p class="p1" style="padding-left: 90px;"><span class="s1">(f) Decompile, reverse engineer, or otherwise attempt to obtain the source code of this Website.</span></p>
<p class="p3">&nbsp;</p>
<p class="p1" style="padding-left: 60px;"><span class="s1">7.3.4 You will be responsible for withholding, filing, and reporting all taxes, duties and other governmental assessments associated with your activity in connection with using this Website and/or the Services.</span></p>
<p class="p1"><span class="s1"> <br /> </span></p>
<p class="p1"><span class="s1">8.&nbsp;Registration and Security<br /> </span></p>
<p class="p1" style="padding-left: 30px;"><span class="s1">8.1 Opening of the Go4sightseeing Account<br /> <br /> </span></p>
<p class="p1" style="padding-left: 60px;"><span class="s1">8.1.1 In the course of using the Services, you may be required to open and maintain an account with Go4sightseeing (&ldquo;Go4sightseeing Account&rdquo;).</span></p>
<p class="p1"><span class="s1"> <br /> <br /> </span></p>
<p class="p1" style="padding-left: 30px;"><span class="s1">8.2 Provision of Personal Information<br /> </span></p>
<p class="p1" style="padding-left: 60px;"><span class="s1">8.2.1 As a condition to using some aspects of the Services, you may be required to register with Go4sightseeing and select a password and user name (&ldquo;Go4sightseeing User ID&rdquo;). If you are accessing the Services through a Third Party Website or service, Go4sightseeing may require that your Go4sightseeing User ID be the same as your user name for such Third Party Website or service.</span></p>
<p class="p1" style="padding-left: 60px;"><span class="s1">8.2.2 You shall provide Go4sightseeing with accurate, complete, and updated registration information. Failure to do so shall constitute a breach of this Terms of Use, which may result in immediate termination of your Go4sightseeing Account.</span></p>
<p class="p1" style="padding-left: 60px;"><span class="s1">8.2.3 You represent that you shall not:</span></p>
<p class="p3" style="padding-left: 60px;">&nbsp;</p>
<p class="p1" style="padding-left: 90px;"><span class="s1">(a) Select or use as a Go4sightseeing User ID a name of another person with the intent to impersonate that person; or</span></p>
<p class="p1" style="padding-left: 90px;"><span class="s1">(b) Use as a Go4sightseeing User ID a name subject to any rights of a person other than you without appropriate authorization.</span></p>
<p class="p3">&nbsp;</p>
<p class="p1" style="padding-left: 60px;"><span class="s1">8.2.4 Go4sightseeing reserves the right to refuse registration of or to cancel a Go4sightseeing Account at its sole discretion. You shall be responsible for maintaining the confidentiality of your password.</span></p>
<p class="p1"><span class="s1"> <br /> </span></p>
<p class="p1"><span class="s1">9.&nbsp;Reviews - Further correspondence - Rights to User Content<br /> </span></p>
<p class="p1" style="padding-left: 30px;"><span class="s1">9.1. By completing a booking, you agree to receive confirmation messages (in the form of emails and/or app notifications), as well as an invitation email(s) or app notification(s) for you to complete our guest review form which we will send to you after you finish an activity. Leaving a review is optional. For clarity, the confirmation and guest review emails are transactional and are not part of the newsletters or marketing mails, from which you can unsubscribe. The completed guest review may be uploaded onto the relevant activity page on the Go4sightseeing platform within 72 hours of the submission for the sole purpose of informing (future) customers of your opinion of the service (level) and quality of the Activity. Upon submitting a review, your account will be awarded Go4sightseeing credits, which may be used towards your next booking subject to terms and conditions. Each account may only submit one review per activity booked once or multiple times within the same calendar month. Fraud and abuse will result in the forfeiture of Go4sightseeing credits. Go4sightseeing further reserves the right to deduct any credits directly from your Go4sightseeing account without prior notice.<br /> </span></p>
<p class="p1" style="padding-left: 30px;"><span class="s1">9.2. By posting a review, you grant Go4sightseeing the full, perpetual, free, transferable and irrevocable rights to all submitted user content. Go4sightseeing reserves the right to translate, edit, adjust, refuse or remove reviews at its sole discretion.<br /> </span></p>
<p class="p1" style="padding-left: 30px;"><span class="s1">9.3. You confirm you will comply with these Guest Review Guidelines. In addition, you represent and warrant that<br /> <br /> </span></p>
<p class="p1" style="padding-left: 30px;"><span class="s1">9.3.1. you own and control all of the rights to the user content that you post or otherwise distribute, or you otherwise have the lawful right to post and distribute such user content to or through the platform;</span></p>
<p class="p1" style="padding-left: 30px;"><span class="s1">9.3.2. such content is accurate and not misleading; and</span></p>
<p class="p1" style="padding-left: 30px;"><span class="s1">9.3.3. use and posting or other transmission of such content does not violate the Terms of Use or any applicable laws and regulations and will not violate any rights of or cause injury to any person or entity.</span></p>
<p class="p1" style="padding-left: 30px;"><span class="s1"> <br /> <br /> </span></p>
<p class="p1" style="padding-left: 30px;"><span class="s1">9.4. Reviews may not contain obscenities, profanity, inappropriate content, hate speech and offensive content, promotion of illegal conduct, other people&rsquo;s personal information such as names, phone numbers or email addresses, and irrelevant content such as promotional, invite and reward information. Moreover, reviews may not defame, abuse, harass, or violate the legal rights of others.<br /> </span></p>
<p class="p1" style="padding-left: 30px;"><span class="s1">9.5. You further grant Go4sightseeing the right to pursue at law any person or entity that violates your or Go4sightseeing's rights in the content by a breach of the Terms of Use. You agree you will be solely responsible for any user content you provide or submit.<br /> </span></p>
<p class="p1" style="padding-left: 30px;"><span class="s1">9.6. Content submitted by users will be considered non-confidential and Go4sightseeing is under no obligation to treat such content as proprietary information. Without limiting the foregoing, Go4sightseeing reserves the right to use the content as it deems appropriate, including, without limitation, deleting, editing, modifying, rejecting, or refusing to post it. Go4sightseeing is under no obligation to offer you any payment for content that you submit or the opportunity to edit, delete or otherwise modify content once it has been submitted to Go4sightseeing. Go4sightseeing shall have no duty to attribute authorship of content to you, and shall not be obligated to enforce any form of attribution by third parties. Please refer to the Terms of Use on the Platform for more details.<br /> </span></p>
<p class="p1"><span class="s1">10.&nbsp;Tickets, Vouchers, Fees and Payment<br /> </span></p>
<p class="p1" style="padding-left: 30px;"><span class="s1">10.1 Purchase and Use of the Vouchers<br /> <br /> </span></p>
<p class="p1" style="padding-left: 60px;"><span class="s1">10.1.1 Through this Website, you may purchase vouchers from Go4sightseeing for the Services (&ldquo;Vouchers&rdquo;) offered by the Operators in the various destinations. Subject to the policy of the relevant Operator, you will receive an email confirmation of your purchase that will contain a Voucher confirmation number (&ldquo;Confirmation Number&rdquo;) and a printable version of your Voucher.</span></p>
<p class="p1" style="padding-left: 60px;"><span class="s1">10.1.2 In order to use your Voucher, you must appear in person at the meeting point designated by the relevant Operator on time, and present such documents and/or information as may be required by the Operator, that may include your Confirmation Number and/or your printed Voucher. If you fail to appear on time or to provide the required documents or information, no refunds will be granted.</span></p>
<p class="p1" style="padding-left: 60px;"><span class="s1">10.1.3 An Operator may also require you to provide an identification document bearing your photo in order to use your Voucher. Neither Go4sightseeing nor the Operator is responsible for lost, destroyed or stolen Vouchers or Confirmation Numbers. Vouchers will be void if the relevant Services to be provided are prohibited by law. If you attempt to use a Voucher in an unlawful manner (e.g., you attempt to use a Voucher for wine tasting when you are under the legal age to do so), the respective Operator may refuse to accept your Voucher, and no refunds will be granted.</span></p>
<p class="p1"><span class="s1"> <br /> <br /> </span></p>
<p class="p1" style="padding-left: 30px;"><span class="s1">10.2 Terms of the Vouchers<br /> <br /> </span></p>
<p class="p1" style="padding-left: 60px;"><span class="s1">10.2.1 The terms of use for each Voucher may vary amongst Operators and any restrictions that apply to the use of such Voucher, including but not limited to a minimum age requirement, will be conveyed to you at the time of purchase on the Website.</span></p>
<p class="p1" style="padding-left: 60px;"><span class="s1">10.2.2 Vouchers are admission tickets to one-time events ('Events'): the date(s) on which a Voucher can be used will be stated on the Voucher. If you do not use your Vouchers on or by the date(s) noted on such Vouchers, except as expressly set forth therein, no refunds will be granted.</span></p>
<p class="p1"><span class="s1"> <br /> <br /> </span></p>
<p class="p1" style="padding-left: 30px;"><span class="s1">10.3 Cancelation of Vouchers<br /> <br /> </span></p>
<p class="p1" style="padding-left: 60px;"><span class="s1">10.3.1 You may cancel your Voucher by contacting Go4sightseeing customer service within the cancelation period, as stated at the time of purchase on the Website. Cancelation windows vary on a case by case basis. A Voucher canceled with the required notice will be refunded in full to the credit card you used to purchase such Voucher.</span></p>
<p class="p1" style="padding-left: 60px;"><span class="s1">10.3.2 The Operator, not Go4sightseeing, is the offeror of the Services for the Events, to which the Vouchers correspond to, and is solely responsible for accepting or rejecting any Voucher you purchase, as related to all such Services.</span></p>
<p class="p1" style="padding-left: 60px;"><span class="s1">10.3.3 Please directly consult with the Operator if you have any enquiries or complaints in respect of the Service you received in connection with your Voucher. Except as expressly set forth herein, all fees paid for Vouchers are non-refundable. Prices quoted for Vouchers are in the currency stated on the Website at the time prior to purchase.</span></p>
<p class="p1" style="padding-left: 60px;"><span class="s1">10.3.4 If an Event which you have purchased a Voucher for is canceled by the Operator, Go4sightseeing will notify you as soon as reasonably practicable, and will process a full refund to the credit card you used to purchase such Voucher.</span></p>
<p class="p1" style="padding-left: 60px;"><span class="s1"> <br /> <br /> </span></p>
<p class="p1" style="padding-left: 30px;"><span class="s1">10.4 Required Assistance<br /> <br /> 10.4.1 If you attempt to use a Voucher in accordance with this Terms of Use and the additional terms and conditions applicable to such Voucher and you are unable to do so (due to the fault of the Operator or otherwise), please contact Go4sightseeing at support@go4sightseeing.com, and Go4sightseeing will try to liaise with the Operator for an appropriate remedy.</span></p>
<p class="p1"><span class="s1"> <br /> <br /> </span></p>
<p class="p1" style="padding-left: 30px;"><span class="s1">10.5 Additional Charges<br /> <br /> </span></p>
<p class="p1" style="padding-left: 60px;"><span class="s1">10.5.1 Go4sightseeing reserves the right to require payment of fees or charges for any Services offered by Go4sightseeing. You shall pay all applicable fees or charges, as described on this Website in connection with such Services selected by you.</span></p>
<p class="p1" style="padding-left: 30px;"><span class="s1"> <br /></span><span class="s1">10.6 Modifications to Charges<br /> <br /> </span></p>
<p class="p1" style="padding-left: 60px;"><span class="s1">10.6.1 Go4sightseeing reserves the right to change its price list for fees or charges at any time, upon notice to you, which may be sent to you by email or posted on this Website. Your use, or continued use, of the Services offered by Go4sightseeing following such notification constitutes your acceptance of any new or revised fees or charges.</span></p>
<p class="p1"><span class="s1"> <br /> <br /> </span></p>
<p class="p1" style="padding-left: 30px;"><span class="s1">10.7 Go4sightseeing&rsquo;s Rights and Obligations<br /> <br /> </span></p>
<p class="p1" style="padding-left: 60px;"><span class="s1">10.7.1 Go4sightseeing reserves the right to deny and cancel bookings or purchases of any Services that are deemed in violation of this policy. Such a determination is at Go4sightseeing&rsquo;s sole discretion.</span></p>
<p class="p1" style="padding-left: 60px;"><span class="s1">10.7.2 Go4sightseeing intends to offer or procure the Operators to offer the Services to you at the best price available on the market. You acknowledge and agree that all taxes and additional fees for particular Services that may be payable for using the Services are expressly excluded in determining the best price.</span></p>
<p class="p1" style="padding-left: 60px;"><span class="s1">10.7.3 Whilst the Operats are required to provide Go4sightseeing with accurate and updated prices of the Services on this Website, Go4sightseeing cannot guarantee that all prices for the Services provided by the Operators are accurate and updated at all times.</span></p>
<p class="p1" style="padding-left: 60px;"><span class="s1"> <br /> </span></p>
<p class="p1" style="padding-left: 60px;"><span class="s1">10.8 The above terms and conditions &amp; return policies are appliable to all Go4sightseeing users worldwide.<br /> </span></p>
<p class="p3" style="padding-left: 60px;">&nbsp;</p>
<p class="p1"><span class="s1">11.&nbsp;Discounts<br /> </span></p>
<p class="p1" style="padding-left: 30px;"><span class="s1">11.1 Go4sightseeing Credits<br /> <br /> </span></p>
<p class="p1" style="padding-left: 60px;"><span class="s1">11.1.1 Go4sightseeing Credits are points that are awarded to you and will be accumulated in your Go4sightseeing Account until expiry. Points are awarded on the actual participated and unrefunded activities purchased from Go4sightseeing&rsquo;s platforms, based on the award program at the time of purchase. Every Ten (10) Go4sightseeing Points carries a value of Hong Kong ONE Dollar (HKD1.00) and the conversion of these Hong Kong Dollar denominated points are based on the exchange rate Go4sightseeing used on the date of your redemption. These points can be used to redeem any of our products on our platform or to reduce the total check out price.</span></p>
<p class="p1" style="padding-left: 60px;"><span class="s1">11.1.2 The Go4sightseeing&rsquo;s Credits may be obtained through the following means and the amount of credit received may vary with each purchase and is at the sole discretion of Go4sightseeing&rsquo;s:<br /> </span></p>
<p class="p1" style="padding-left: 60px;"><span class="s1">(a) Rebates from previous purchases</span></p>
<p class="p1" style="padding-left: 60px;"><span class="s1">(b) Receiving the credit through any authorized means, determined at Go4sightseeing&rsquo;s discretion</span></p>
<p class="p1" style="padding-left: 60px;"><span class="s1">(c) Upon submitting the review after successfully completing Go4sightseeing&rsquo;s experience you purchased (not applicable to activities priced at 0, such as free vouchers)</span></p>
<p class="p3" style="padding-left: 60px;">&nbsp;</p>
<p class="p1" style="padding-left: 60px;"><span class="s1">11.1.3 If you've completed the same activity more than once in the same month, you will only get credits for the first review you leave for that activity.</span></p>
<p class="p1" style="padding-left: 60px;"><span class="s1">11.1.4 All Go4sightseeing Credits obtained anytime in the first calendar year will expire on the last day of the next calendar year. Therefore, if you are awarded the credit on 1 October 2017, your credits will expire and therefore be removed from your account on 31 December 2018. All the credits accumulated to date as of 25 September 2017, regardless of when you obtained the credits and is remained unused will be expired on 31 December 2018.</span></p>
<p class="p1" style="padding-left: 30px;"><span class="s1"> <br /> <br /> </span></p>
<p class="p1" style="padding-left: 30px;"><span class="s1">11.2 Go4sightseeing Coupons<br /> <br /> </span></p>
<p class="p1" style="padding-left: 60px;"><span class="s1">11.2.1 Go4sightseeing Coupons are coupons with a one-time use that will be sent to your designated email address or applied directly to your Go4sightseeing Account, which may be used in exchange for discounts off future bookings on the Go4sightseeing Booking Platform.</span></p>
<p class="p1" style="padding-left: 60px;"><span class="s1">11.2.2 Go4sightseeing Credits may be attained through the following means:<br /> </span></p>
<p class="p1" style="padding-left: 60px;"><span class="s1">(a) You may receive Go4sightseeing Coupons through the Go4sightseeing Referral Program, as further elaborated on in Clause 11; or</span></p>
<p class="p1" style="padding-left: 60px;"><span class="s1">(b) You may receive Go4sightseeing Coupons by other authorized means as determined at Go4sightseeing&rsquo;s sole discretion.</span></p>
<p class="p1"><span class="s1"> <br /> <br /> </span></p>
<p class="p1" style="padding-left: 30px;"><span class="s1">11.3 Abuse of Discounts<br /> </span></p>
<p class="p1" style="padding-left: 60px;"><span class="s1">11.3.1 In the event where it has come to Go4sightseeing&rsquo;s attention that the Go4sightseeing Credits or Go4sightseeing Coupons were earned in a fraudulent manner, in a manner that violates this Terms of Use or in a manner otherwise not intended by Go4sightseeing, Go4sightseeing reserves the right to the following:</span></p>
<p class="p3">&nbsp;</p>
<p class="p1" style="padding-left: 90px;"><span class="s1">(a) Termination of your Go4sightseeing Account with immediate effect; or</span></p>
<p class="p1" style="padding-left: 90px;"><span class="s1">(b) Cancelation of all Go4sightseeing Credits or Go4sightseeing Coupons as previously accrued; or</span></p>
<p class="p1" style="padding-left: 90px;"><span class="s1">(c) Refusal of the provision of the Services to you; or</span></p>
<p class="p1" style="padding-left: 90px;"><span class="s1">(d) Any other measures as deemed appropriate by Go4sightseeing at its sole discretion.</span></p>
<p class="p1" style="padding-left: 90px;"><span class="s1"> <br /> </span></p>
<p class="p1"><span class="s1">12.&nbsp;Go4sightseeing Referral Program<br /> </span></p>
<p class="p1" style="padding-left: 30px;"><span class="s1">12.1 The Program<br /> <br /> </span></p>
<p class="p1" style="padding-left: 60px;"><span class="s1">12.1.1 On certain Go4sightseeing Sites, Go4sightseeing may offer members the chance to earn Go4sightseeing Coupons, when they invite friends to become members of a Go4sightseeing Site and those friends make a confirmed booking through an authorized Go4sightseeing invitation channel (&ldquo;Go4sightseeing Authorized Channel&rdquo;) (e.g. an invitation sent through Go4sightseeing&rsquo;s website, Facebook or another social media channel as supported by Go4sightseeing).</span></p>
<p class="p1"><span class="s1"> <br /> <br /> </span></p>
<p class="p1" style="padding-left: 30px;"><span class="s1">12.2 Terms<br /> </span></p>
<p class="p1" style="padding-left: 60px;"><span class="s1">12.2.1 You may only earn Go4sightseeing Coupons via Go4sightseeing&rsquo;s authorized member invite mechanisms. Referrals outside of Go4sightseeing Authorized Channel will not result in any Go4sightseeing Coupons. You understand that Go4sightseeing Coupons are not transferable, may not be auctioned, bartered or sold, and may not be pooled with other members.</span></p>
<p class="p1" style="padding-left: 60px;"><span class="s1">12.2.2 You will only receive Go4sightseeing Coupons for the first confirmed booking made by a friend who makes his or her first booking on the Go4sightseeing Sites and subsequently completes his or her first booking as a result of an invite from you via a Go4sightseeing Authorized Channel. If your friend does not follow the directions in the invite email or other valid invite mechanism to accept the invitation, you may not receive Go4sightseeing Coupons, and Go4sightseeing will have no liability to you for your friend&rsquo;s failure to follow directions.</span></p>
<p class="p1" style="padding-left: 60px;"><span class="s1">12.2.3 You agree that having multiple Go4sightseeing Accounts is a violation of this Terms of Use and that sending invites to alternate email addresses or accounts or otherwise attempting to circumvent the Go4sightseeing Referral Program system may, without limiting any of Go4sightseeing&rsquo;s other rights or remedies, result in forfeiture of your membership and all Go4sightseeing Coupons in your Go4sightseeing Account.</span></p>
<p class="p1" style="padding-left: 60px;"><span class="s1">12.2.4 You must not conduct your own promotion in connection with the Go4sightseeing Referral Program. You may not engage in any promotional, marketing, or other advertising activities on behalf of Go4sightseeing, including the use of any trademarks of Go4sightseeing.</span></p>
<p class="p1" style="padding-left: 60px;"><span class="s1">12.2.5 Go4sightseeing reserves the right to void referrals and Go4sightseeing Coupons earned if it is suspected that the referrals or Go4sightseeing Coupons were earned in a fraudulent manner, in a manner that violates this Terms of Use or in a manner otherwise not intended by Go4sightseeing.</span></p>
<p class="p1" style="padding-left: 60px;"><span class="s1">12.2.6 Go4sightseeing Coupons will be emailed to your designated email address within 24 hours of one of your qualifying invitees completing his or her confirmed booking on Go4sightseeing&rsquo;s website</span></p>
<p class="p1" style="padding-left: 60px;"><span class="s1">12.2.7 Go4sightseeing reserves the right to modify the values and rewards of the Go4sightseeing Referral Program based on each user's activity.</span></p>
<p class="p1" style="padding-left: 60px;"><span class="s1">12.2.8 Go4sightseeing Referral Program is void where prohibited by law. Go4sightseeing reserves the right to modify or terminate the Go4sightseeing Referral Program at any time. Should there be any tax liability for the accumulation and/or use of Go4sightseeing Coupons, such taxes are the sole responsibility of the participant. You understand that your Go4sightseeing Account may not accurately reflect the Go4sightseeing Coupons you have actually earned. Go4sightseeing will have no liability for any errors displayed in your Go4sightseeing Account.</span></p>
<p class="p1" style="padding-left: 90px;"><span class="s1"> <br /> </span></p>
<p class="p1"><span class="s1">13.&nbsp;Privacy Policy<br /> </span></p>
<p class="p1" style="padding-left: 30px;"><span class="s1">13.1 Privacy Policy<br /> </span></p>
<p class="p1" style="padding-left: 60px;"><span class="s1">13.1.1 For Go4sightseeing&rsquo;s policy relating to its use of of your personal data, please review Go4sightseeing&rsquo;s current Privacy Policy, which is hereby incorporated by reference to this Terms of Use. Your acceptance of this Terms of Use constitutes your acceptance and agreement to be bound by our Privacy Policy.</span></p>
<p class="p1"><span class="s1"> <br /> </span></p>
<p class="p1"><span class="s1">14.&nbsp;Indemnity<br /> </span></p>
<p class="p1" style="padding-left: 30px;"><span class="s1">14.1 Go4sightseeing&rsquo;s Indemnification<br /> <br /> </span></p>
<p class="p1" style="padding-left: 60px;"><span class="s1">14.1.1 You will indemnify and hold Go4sightseeing, our holding companies, subsidiaries, affiliates, officers, directors and employees harmless from, including but not limited to all damages, liabilities, settlements, costs and attorney&rsquo;s fees, claims or demands made by any third party due to or arising out of your access to this Website, use of this Website, your violation of this Terms of Use, or the infringement of any intellectual property or other right of any person or entity by you or any third party using your Go4sightseeing User ID.</span></p>
<p class="p1"><span class="s1"> <br /> <br /> </span></p>
<p class="p1" style="padding-left: 30px;"><span class="s1">14.2 Go4sightseeing&rsquo;s Involvement<br /> </span></p>
<p class="p1" style="padding-left: 60px;"><span class="s1">14.2.1 Go4sightseeing may, if necessary, participate in the defense of any claim or action and any negotiations for settlement. You will not make any settlement that may adversely affect the rights or obligations of Go4sightseeing without Go4sightseeing&rsquo;s prior written approval. Go4sightseeing reserves the right, at its expense and upon notice to you to assume exclusive defense and control of any claim or action.</span></p>
<p class="p1"><span class="s1"> <br /> </span></p>
<p class="p1"><span class="s1">15.&nbsp;Disclaimers and Limitation of Liability<br /> </span></p>
<p class="p1" style="padding-left: 30px;"><span class="s1">15.1 Parties&rsquo; Relationship<br /> <br /> </span></p>
<p class="p1" style="padding-left: 30px;"><span class="s1">15.1.1 Go4sightseeing has no special relationship with or fiduciary duty to you for accessing and using this Website and the Content. You acknowledge that Go4sightseeing has no control over, and no duty to take any action regarding:<br /> </span></p>
<p class="p1" style="padding-left: 60px;"><span class="s1">(a) Which users gain access to this Website;</span></p>
<p class="p1" style="padding-left: 60px;"><span class="s1">b) What content you access via this Website;</span></p>
<p class="p1" style="padding-left: 60px;"><span class="s1">(c) What effects the Content may have on you;</span></p>
<p class="p1" style="padding-left: 60px;"><span class="s1">(d) How you may interpret or use the Content; and</span></p>
<p class="p1" style="padding-left: 60px;"><span class="s1">(e) What actions you may take as a result of having been exposed to the Content.</span></p>
<p class="p1" style="padding-left: 60px;"><span class="s1"> <br /> <br /> </span></p>
<p class="p1" style="padding-left: 30px;"><span class="s1">15.2 Services and Comments<br /> <br /> </span></p>
<p class="p1" style="padding-left: 60px;"><span class="s1">15.2.1 You acknowledge and agree that the Operators may offer the Services on this Website, and that suggestions or recommendations may be given by the Operators or Users of this Website. Go4sightseeing makes no representations or warranties regarding the accuracy of descriptions anywhere on the Services, or regarding suggestions or recommendations of the Services offered or purchased through this Website.</span></p>
<p class="p1"><span class="s1"> <br /> <br /> </span></p>
<p class="p1" style="padding-left: 30px;"><span class="s1">15.3 Exemption of Liability<br /> <br /> </span></p>
<p class="p1" style="padding-left: 60px;"><span class="s1">15.3.1 In no event will Go4sightseeing, this Website, or any of Go4sightseeing&rsquo;s holding companies, subsidiaries, affiliates, officers, directors and/or employees be liable for any loss of profits or any indirect, consequential, special, incidental, or punitive damages arising out of, based on, or resulting from:<br /> </span></p>
<p class="p1" style="padding-left: 90px;"><span class="s1">(a) This Website; or</span></p>
<p class="p1" style="padding-left: 90px;"><span class="s1">(b) This Terms of Use; or</span></p>
<p class="p1" style="padding-left: 90px;"><span class="s1">(c) Any breach of this Terms of Use by you or a third party; or</span></p>
<p class="p1" style="padding-left: 90px;"><span class="s1">(d) Use of this Website, tools or Services we provide related to the business we operate on this Website by you or any third party; or</span></p>
<p class="p1" style="padding-left: 90px;"><span class="s1">(e) Any actual or attempted communication or transaction between users, in each case, even if we have been advised of the possibility of such damages.</span></p>
<p class="p3" style="padding-left: 90px;">&nbsp;</p>
<p class="p1" style="padding-left: 30px;"><span class="s1">15.3.2 These limitations and exclusions apply without regard to whether the damages arise from:<br /> </span></p>
<p class="p1" style="padding-left: 60px;"><span class="s1">a) Breach of contract; or</span></p>
<p class="p1" style="padding-left: 60px;"><span class="s1">(b) Breach of warranty; or</span></p>
<p class="p1" style="padding-left: 60px;"><span class="s1">(c) Strict liability; or</span></p>
<p class="p1" style="padding-left: 60px;"><span class="s1">(d) Tort; or</span></p>
<p class="p1" style="padding-left: 60px;"><span class="s1">(e) Negligence; or</span></p>
<p class="p1" style="padding-left: 60px;"><span class="s1">(f) Any other cause of action, to the maximum extent that such exclusion and limitations are not prohibited by applicable law.</span></p>
<p class="p3" style="padding-left: 60px;">&nbsp;</p>
<p class="p1" style="padding-left: 30px;"><span class="s1">15.3.3 This Website, including all content, software, functions, materials and information made available on or accessed through this Website, is provided on an "as is" basis. To the fullest extent permissible by applicable law, Go4sightseeing makes no representations or warranties of any kind, either express or implied, including but not limited to the content on this Website or the materials, information and functions made accessible through this Website, for any of the Services or hypertext links to third parties or for any breach of security associated with the transmission of sensitive information through this Website, or for Operator ability, fitness for a particular purpose, non-infringement, or that the use of the Services will be uninterrupted or error-free.</span></p>
<p class="p1" style="padding-left: 30px;"><span class="s1">15.3.6 You acknowledge and agree that any transmission to and from this Website is not confidential and your communications may be read or intercepted by others. You further acknowledge and agree that by submitting communications to Go4sightseeing and by posting information on this Website, including tours and/or activities, no confidential, fiduciary, contractually implied or other relationship is created between you and Go4sightseeing other than pursuant to this Terms of Use.</span></p>
<p class="p1" style="padding-left: 30px;"><span class="s1">15.3.7 You acknowledge and agree that you will not hold or seek to hold Go4sightseeing responsible for the content provided by any Operator or third party and you further acknowledge and agree that Go4sightseeing is not a party to any transaction in relation to the Services provided by any Operator or third party. Go4sightseeing has no control over and does not guarantee the safety of any transaction, tours and/or activities or the truth or accuracy of any listing or other content provided by any Operator or third party on this Website.</span></p>
<p class="p1" style="padding-left: 30px;"><span class="s1"> <br /> <br /> </span></p>
<p class="p1" style="padding-left: 30px;"><span class="s1">15.4 Remedies<br /> </span></p>
<p class="p1" style="padding-left: 60px;"><span class="s1">15.4.1 If you are dissatisfied with this Website, do not agree with any part of this Terms of Use, or have any other dispute or claim with or against Go4sightseeing or another user of this Website with respect to this Terms of Use or this Website, your sole and exclusive remedy against Go4sightseeing is to discontinue use of this Website.</span></p>
<p class="p1" style="padding-left: 60px;"><span class="s1">15.4.2 In any event, to the fullest extent permissible by the applicable law, Go4sightseeing&rsquo;s liability, and the liability of any member of Go4sightseeing, to you or any third party in any circumstance arising out of or in connection with this Website is limited to the greater of:</span></p>
<p class="p3" style="padding-left: 60px;">&nbsp;</p>
<p class="p1" style="padding-left: 90px;"><span class="s1">(a) The amount of fees you paid to Go4sightseeing in the twelve months prior to the action giving rise to liability; or</span></p>
<p class="p1" style="padding-left: 90px;"><span class="s1">(b) Hong Kong Dollars 500.00 in the aggregate for all claims.</span></p>
<p class="p1" style="padding-left: 90px;"><span class="s1"> <br /> </span></p>
<p class="p1"><span class="s1">16.&nbsp;Interaction with Third Parties<br /> </span></p>
<p class="p1" style="padding-left: 30px;"><span class="s1">16.1 Links to Third Party Websites<br /> <br /> </span></p>
<p class="p1" style="padding-left: 60px;"><span class="s1">16.1.1 This Website may contain links to third party websites or services (&ldquo;Third Party Websites&rdquo;) that are not owned or controlled by Go4sightseeing, or the Services may be accessible by logging in through a Third Party Website. Links to Third Party Websites do not constitute an endorsement or recommendation by Go4sightseeing of such Third Party Websites or the information, products, advertising or other materials available on those Third Party Websites.</span></p>
<p class="p1" style="padding-left: 60px;"><span class="s1">16.1.2 When you access Third Party Websites, you do so at your own risk. You hereby represent and warrant that you have read and agree to be bound by all applicable policies of any Third Party Websites relating to your use of the Services and that you will act in accordance with those policies, in addition to your obligations under this Terms of Use.</span></p>
<p class="p1" style="padding-left: 60px;"><span class="s1">16.1.3 Go4sightseeing has no control over, and assumes no responsibility for, the content, accuracy, privacy policies, or practices of or opinions expressed in any Third Party Websites. In addition, Go4sightseeing will not and cannot monitor, verify, censor or edit the content of any Third Party Website. By using the Services, you expressly relieve and hold Go4sightseeing harmless from any and all liability arising from your use of any Third Party Website.</span></p>
<p class="p1" style="padding-left: 60px;"><span class="s1">16.1.4 Your interactions with organizations and/or individuals found on or through the Services including but not limited to the Operators, including payment and delivery of goods or services, and any other terms, conditions, warranties or representations associated with such dealings, are solely between you and such organizations and/or individuals.</span></p>
<p class="p1" style="padding-left: 60px;"><span class="s1">16.1.5 You should conduct whatever investigation you feel necessary or appropriate before proceeding with any online or offline transaction with any of these third parties.</span></p>
<p class="p1" style="padding-left: 60px;"><span class="s1"> <br /> <br /> </span></p>
<p class="p1" style="padding-left: 30px;"><span class="s1">16.2 Go4sightseeing&rsquo;s Responsibility<br /> </span></p>
<p class="p1" style="padding-left: 60px;"><span class="s1">16.2.1 You agree that Go4sightseeing shall not be responsible or liable for any loss or damage of any sort incurred as the result of any such dealings. If there is a dispute between participants on this site, or between users and any third party, you understand and agree that Go4sightseeing is under no obligation to become involved. In the event that you have a dispute with one or more other users or third parties, you hereby release Go4sightseeing, its holding companies, subsidiaries, officers, directors, employees, agents, and successors in rights from claims, demands, and damages (actual and consequential) of every kind or nature, known or unknown, suspected or unsuspected, disclosed or undisclosed, arising out of or in any way related to such disputes.</span></p>
<p class="p1" style="padding-left: 60px;"><span class="s1"> <br /> </span></p>
<p class="p1"><span class="s1">17.&nbsp;Termination<br /> </span></p>
<p class="p1" style="padding-left: 30px;"><span class="s1">17.1 Termination by Go4sightseeing<br /> <br /> </span></p>
<p class="p1" style="padding-left: 60px;"><span class="s1">17.1.1 This Terms of Use shall remain in full force and effect while you use this Websites or the Services. Go4sightseeing may terminate or suspend your access to the Services or your membership at any time, for any reason, and without notice, which may result in the forfeiture and destruction of all information associated with your membership. Go4sightseeing may also terminate or suspend any and all Services and access to this Website immediately, without prior notice or liability, if you breach any of the terms or conditions of this Terms of Use.</span></p>
<p class="p1" style="padding-left: 30px;"><span class="s1"> <br /></span><span class="s1">17.2 Effects of Termination<br /> </span></p>
<p class="p1" style="padding-left: 60px;"><span class="s1">17.2.1 Upon termination of your Go4sightseeing Account, your right to use the Services, access this Website, and any Content will immediately cease. All provisions of this Terms of Use which, by their nature, should survive termination, shall survive termination, including but not limited to ownership provisions, warranty disclaimers, and limitations of liability.</span></p>
<p class="p1" style="padding-left: 60px;"><span class="s1">17.2.2 If this Terms of Use is terminated as a result of your breach, Go4sightseeing reserves the right to cancel any outstanding Vouchers you may have purchased prior to said termination, without refund or liability to you.</span></p>
<p class="p1" style="padding-left: 60px;"><span class="s1"> <br /> </span></p>
<p class="p1"><span class="s1">18.&nbsp;Passports, Visas &amp; Insurances<br /> </span></p>
<p class="p1" style="padding-left: 30px;"><span class="s1">18.1 Your Responsibilities<br /> </span></p>
<p class="p1" style="padding-left: 30px;"><span class="s1">18.1.1 It is the responsibility of all passengers, regardless of nationality and destination, to check with the consulate of the country they are visiting for current entry requirements.</span></p>
<p class="p1" style="padding-left: 30px;"><span class="s1">18.1.2 As visa and health requirements are subject to changes without notice, Go4sightseeing recommends that you verify health and visa requirements with the appropriate consulate prior to departure.</span></p>
<p class="p1" style="padding-left: 30px;"><span class="s1">18.1.3 Go4sightseeing strongly recommends that you purchase a comprehensive travel insurance policy prior to departure.</span></p>
<p class="p1" style="padding-left: 30px;"><span class="s1"> <br /> </span></p>
<p class="p1"><span class="s1">19.&nbsp;Governing Law &amp; Jurisdiction<br /> </span></p>
<p class="p1" style="padding-left: 30px;"><span class="s1">19.1 Governing Law<br /> </span></p>
<p class="p1" style="padding-left: 30px;"><span class="s1">19.1.1 This Terms of Use shall be governed by the laws of Hong Kong Special Administrative Region of the Peoples Republic of China. You agree to submit to the non-exclusive jurisdiction of the Hong Kong court.<br /> </span></p>
<p class="p1" style="padding-left: 30px;"><span class="s1">jurisdiction of the Hong Kong court.Go4sightseeing Travel Technology Limited acknowledges and agrees that it delegates all contractual responsibility in respect of such Operations to its affiliates as follow:</span></p>
<p class="p1" style="padding-left: 60px;"><span class="s1">a. In respect of all transactions occurring in Singapore, Go4sightseeing Travel Technology Pte Ltd is the responsible contractual party in respect of the above Operations;</span></p>
<p class="p1" style="padding-left: 60px;"><span class="s1">b. In respect of all transactions occurring in Taiwan, Go4sightseeing Travel Taiwan Limited is the responsible contractual party in respect of the above Operations;</span></p>
<p class="p1" style="padding-left: 60px;"><span class="s1">c. In respect of all transactions occurring in Korea, Go4sightseeing Travel Technology LLC is the responsible contractual party in respect of the above Operations;</span></p>
<p class="p1" style="padding-left: 60px;"><span class="s1">d. In respect of all other transactions, Go4sightseeing Travel Technology Limited is the responsible contractual party in respect of the above Operations.</span></p>
<p class="p1" style="padding-left: 60px;"><span class="s1"> <br /> </span></p>
<p class="p1"><span class="s1">20.&nbsp;Miscellaneous<br /> </span></p>
<p class="p1" style="padding-left: 30px;"><span class="s1">20.1 Severability<br /> <br /> </span></p>
<p class="p1" style="padding-left: 60px;"><span class="s1">20.1.1 If any provision of this Terms of Use is found to be unenforceable or invalid, that provision shall be limited or eliminated to the minimum extent necessary so that this Terms of Use shall otherwise remain in full force and effect and enforceable.</span></p>
<p class="p1"><span class="s1"> <br /> <br /> </span></p>
<p class="p1" style="padding-left: 30px;"><span class="s1">20.2 Assignment<br /> </span></p>
<p class="p1" style="padding-left: 60px;"><span class="s1">20.2.1 This Terms of Use is not assignable, transferable or sub-licensable by you except with Go4sightseeing&rsquo;s prior written consent. Go4sightseeing may transfer, assign or delegate this Terms of Use and its rights and obligations without prior notice to you.</span></p>
<p class="p1"><span class="s1"> <br /> </span></p>
<p class="p1"><span class="s1">21.&nbsp;Contact<br /> </span></p>
<p class="p1" style="padding-left: 30px;"><span class="s1">21.1 Please contact Go4sightseeing at support@go4sightseeing.com to report any violations of this Terms of Use or to pose any questions regarding this Terms of Use or the Service.<br /> </span></p>
<p class="p1" style="padding-left: 30px;"><span class="s1">Last updated on 6 Feb 2018</span></p>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="container h-100 padding-top-lg padding-bottom-lg">
      <div class="row h-100">
        <div class="t_and_c_content padding-sm">
          <p><strong>Go4SightSeeing </strong>is fast and fun way to explore and book unique Sight Seen, Shows, Activities and Experiences at the Lowest Prices Guaranteed.With just a few clicks, get ready to enjoy the Siam Nimrat show no big queues to get tickets , enjoy Santosa isLand under water park and other attractions.So Just click book and go to your favourite destination.</p>
          <h2>What is special and great about BMSS</h2>
          <ul>
            <li>Easy way to explore new shows , sight seen, locations which click of button you can book it. </li>
            <li>Easy cancellation no charges if cancel 48 hours before show.</li>
            <li>Lowest price guaranteed.</li>
            <li>Easy confirmation and paperless e-tickets for many popular attractions</li>
            <li>Secure and easy booking and safe payment with credit cards or debit cards.</li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
export default {

}
</script>

<style lang="css">
.banner_t_and_c{
  background: url("/images/frontimages/top-banner-bg.png") !important;
  height: 70vh;
  min-height: 65vh;
  padding-top: 0;
  padding-bottom: 0;
  position: relative;
  width: 100%;
}
</style>
